kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mlboy/micro-service

steps:
  - name: build
    image: golang:1.11-alpine
    commands:
      - pwd
      - go build -v -o /go/bin/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
      # - go build -v -o /go/bin/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
      # - go build -v -o /go/bin/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
      - ls
    when:
      event:
        - push
        - tag
  - name: docker
    image: plugins/docker
    settings:
      context: /go/bin
      auto_tag: true
      username: 415235169
      password: maliang1224
      dockerfile: dockerfile.d/pay-srv/Dockerfile
      repo: hub.tencentyun.com/micro/pay-srv
      registry: hub.tencentyun.com