kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mlboy/micro-service

steps:
  - name: build
    image: golang:1.11-alpine
    commands:
      - go build -v -o ./dist/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
      - go build -v -o ./dist/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
      - go build -v -o ./dist/pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go
    when:
      event:
        - push
        - tag
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      username: #415235169
        from_secret: hub_username
      password: #maliang1224
        from_secret: hub_password
      dockerfile: dockerfile.d/pay-srv/Dockerfile
      repo: hub.tencentyun.com/micro/pay-srv
      registry: hub.tencentyun.com