kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mlboy/micro-service

steps:
  - name: build
    image: golang:1.11-alpine
    commands:
      - go build -v -o micro-pay-srv  -gcflags '-N -l' ./service/pay-srv/*.go