// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay_srv/pay.proto

package pay_srv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	OutTradeNo           string   `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	TotalFee             int64    `protobuf:"varint,5,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	TradeType            string   `protobuf:"bytes,6,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	Subject              string   `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	FromIp               string   `protobuf:"bytes,8,opt,name=from_ip,json=fromIp,proto3" json:"from_ip,omitempty"`
	CreateAt             int64    `protobuf:"varint,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Extra                string   `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,11,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{0}
}
func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (dst *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(dst, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CreateReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateReq) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *CreateReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CreateReq) GetTotalFee() int64 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *CreateReq) GetTradeType() string {
	if m != nil {
		return m.TradeType
	}
	return ""
}

func (m *CreateReq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateReq) GetFromIp() string {
	if m != nil {
		return m.FromIp
	}
	return ""
}

func (m *CreateReq) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *CreateReq) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *CreateReq) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

type PayField struct {
	AppId      string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	OutTradeNo string `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TradeNo    string `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	TotalFee   int64  `protobuf:"varint,4,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	//    string trade_type = 5;   //交易方式 (JSAPI\NATIVE)
	CodeUrl              string   `protobuf:"bytes,5,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`
	FieldStr             string   `protobuf:"bytes,6,opt,name=field_str,json=fieldStr,proto3" json:"field_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayField) Reset()         { *m = PayField{} }
func (m *PayField) String() string { return proto.CompactTextString(m) }
func (*PayField) ProtoMessage()    {}
func (*PayField) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{1}
}
func (m *PayField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayField.Unmarshal(m, b)
}
func (m *PayField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayField.Marshal(b, m, deterministic)
}
func (dst *PayField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayField.Merge(dst, src)
}
func (m *PayField) XXX_Size() int {
	return xxx_messageInfo_PayField.Size(m)
}
func (m *PayField) XXX_DiscardUnknown() {
	xxx_messageInfo_PayField.DiscardUnknown(m)
}

var xxx_messageInfo_PayField proto.InternalMessageInfo

func (m *PayField) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PayField) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *PayField) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

func (m *PayField) GetTotalFee() int64 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *PayField) GetCodeUrl() string {
	if m != nil {
		return m.CodeUrl
	}
	return ""
}

func (m *PayField) GetFieldStr() string {
	if m != nil {
		return m.FieldStr
	}
	return ""
}

type PayRsp struct {
	Provider             string    `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Channel              string    `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	PayField             *PayField `protobuf:"bytes,3,opt,name=pay_field,json=payField,proto3" json:"pay_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PayRsp) Reset()         { *m = PayRsp{} }
func (m *PayRsp) String() string { return proto.CompactTextString(m) }
func (*PayRsp) ProtoMessage()    {}
func (*PayRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{2}
}
func (m *PayRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayRsp.Unmarshal(m, b)
}
func (m *PayRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayRsp.Marshal(b, m, deterministic)
}
func (dst *PayRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayRsp.Merge(dst, src)
}
func (m *PayRsp) XXX_Size() int {
	return xxx_messageInfo_PayRsp.Size(m)
}
func (m *PayRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PayRsp proto.InternalMessageInfo

func (m *PayRsp) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *PayRsp) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PayRsp) GetPayField() *PayField {
	if m != nil {
		return m.PayField
	}
	return nil
}

type NotifyReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Raw                  string   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReq) Reset()         { *m = NotifyReq{} }
func (m *NotifyReq) String() string { return proto.CompactTextString(m) }
func (*NotifyReq) ProtoMessage()    {}
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{3}
}
func (m *NotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReq.Unmarshal(m, b)
}
func (m *NotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReq.Marshal(b, m, deterministic)
}
func (dst *NotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReq.Merge(dst, src)
}
func (m *NotifyReq) XXX_Size() int {
	return xxx_messageInfo_NotifyReq.Size(m)
}
func (m *NotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReq proto.InternalMessageInfo

func (m *NotifyReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *NotifyReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *NotifyReq) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

type NotifyRsp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	OutTradeNo           string   `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRsp) Reset()         { *m = NotifyRsp{} }
func (m *NotifyRsp) String() string { return proto.CompactTextString(m) }
func (*NotifyRsp) ProtoMessage()    {}
func (*NotifyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{4}
}
func (m *NotifyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRsp.Unmarshal(m, b)
}
func (m *NotifyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRsp.Marshal(b, m, deterministic)
}
func (dst *NotifyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRsp.Merge(dst, src)
}
func (m *NotifyRsp) XXX_Size() int {
	return xxx_messageInfo_NotifyRsp.Size(m)
}
func (m *NotifyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRsp proto.InternalMessageInfo

func (m *NotifyRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *NotifyRsp) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

type QueryReq struct {
	OutTradeNo           string   `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{5}
}
func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (dst *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(dst, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

// 支付通知事件
type NotifyEvent struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Data                 *PostData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NotifyEvent) Reset()         { *m = NotifyEvent{} }
func (m *NotifyEvent) String() string { return proto.CompactTextString(m) }
func (*NotifyEvent) ProtoMessage()    {}
func (*NotifyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{6}
}
func (m *NotifyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyEvent.Unmarshal(m, b)
}
func (m *NotifyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyEvent.Marshal(b, m, deterministic)
}
func (dst *NotifyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyEvent.Merge(dst, src)
}
func (m *NotifyEvent) XXX_Size() int {
	return xxx_messageInfo_NotifyEvent.Size(m)
}
func (m *NotifyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyEvent proto.InternalMessageInfo

func (m *NotifyEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotifyEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NotifyEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotifyEvent) GetData() *PostData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostData struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostData) Reset()         { *m = PostData{} }
func (m *PostData) String() string { return proto.CompactTextString(m) }
func (*PostData) ProtoMessage()    {}
func (*PostData) Descriptor() ([]byte, []int) {
	return fileDescriptor_pay_4ed943f6dc6bbc48, []int{7}
}
func (m *PostData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostData.Unmarshal(m, b)
}
func (m *PostData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostData.Marshal(b, m, deterministic)
}
func (dst *PostData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostData.Merge(dst, src)
}
func (m *PostData) XXX_Size() int {
	return xxx_messageInfo_PostData.Size(m)
}
func (m *PostData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostData.DiscardUnknown(m)
}

var xxx_messageInfo_PostData proto.InternalMessageInfo

func (m *PostData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PostData) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReq)(nil), "pay_srv.CreateReq")
	proto.RegisterType((*PayField)(nil), "pay_srv.PayField")
	proto.RegisterType((*PayRsp)(nil), "pay_srv.PayRsp")
	proto.RegisterType((*NotifyReq)(nil), "pay_srv.NotifyReq")
	proto.RegisterType((*NotifyRsp)(nil), "pay_srv.NotifyRsp")
	proto.RegisterType((*QueryReq)(nil), "pay_srv.QueryReq")
	proto.RegisterType((*NotifyEvent)(nil), "pay_srv.NotifyEvent")
	proto.RegisterType((*PostData)(nil), "pay_srv.PostData")
}

func init() { proto.RegisterFile("pay_srv/pay.proto", fileDescriptor_pay_4ed943f6dc6bbc48) }

var fileDescriptor_pay_4ed943f6dc6bbc48 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xbf, 0x9c, 0x1c, 0x7b, 0x52, 0x7d, 0xd0, 0x15, 0x87, 0x6d, 0x01, 0xa9, 0x58, 0x42,
	0xea, 0x05, 0xa4, 0xa8, 0x3c, 0x01, 0x82, 0x56, 0xea, 0x4d, 0x55, 0xdc, 0xf4, 0xda, 0xda, 0xda,
	0x13, 0x61, 0x70, 0xbc, 0xcb, 0x7a, 0x12, 0xf0, 0xdb, 0xf0, 0x0e, 0xbc, 0x04, 0x8f, 0x85, 0x76,
	0x76, 0x93, 0x9e, 0x40, 0xbd, 0x9b, 0xf9, 0x4f, 0x76, 0x0e, 0xbf, 0x99, 0x18, 0xb6, 0x8d, 0xea,
	0xf2, 0xd6, 0xae, 0x0e, 0x8c, 0xea, 0xa6, 0xc6, 0x6a, 0xd2, 0x62, 0x1c, 0xa4, 0xf4, 0x77, 0x1f,
	0x92, 0x0f, 0x16, 0x15, 0x61, 0x86, 0xdf, 0xc4, 0x33, 0x48, 0x8a, 0xba, 0xc2, 0x86, 0xf2, 0xaa,
	0x94, 0xbd, 0xbd, 0xde, 0x7e, 0x92, 0xc5, 0x5e, 0x38, 0x29, 0xc5, 0x4b, 0xd8, 0x52, 0x45, 0x81,
	0x6d, 0x9b, 0x93, 0xfe, 0x8a, 0x8d, 0xec, 0x73, 0x7c, 0xe2, 0xb5, 0x99, 0x93, 0xc4, 0x1e, 0x6c,
	0xe9, 0x25, 0xe5, 0x64, 0x55, 0x89, 0x79, 0xa3, 0xe5, 0x80, 0x7f, 0x02, 0x7a, 0x49, 0x33, 0x27,
	0x9d, 0x6a, 0x21, 0x61, 0x5c, 0x7c, 0x56, 0x4d, 0x83, 0xb5, 0x1c, 0x72, 0x70, 0xed, 0xba, 0xda,
	0xa4, 0x49, 0xd5, 0xf9, 0x1c, 0x51, 0x8e, 0xf6, 0x7a, 0xfb, 0x83, 0x2c, 0x66, 0xe1, 0x18, 0x51,
	0xbc, 0x00, 0xf0, 0x49, 0xa9, 0x33, 0x28, 0x23, 0x7e, 0x99, 0xb0, 0x32, 0xeb, 0x0c, 0xba, 0xac,
	0xed, 0xf2, 0xf2, 0x0b, 0x16, 0x24, 0xc7, 0x3e, 0x6b, 0x70, 0xc5, 0x53, 0x18, 0xcf, 0xad, 0x5e,
	0xe4, 0x95, 0x91, 0x31, 0x47, 0x22, 0xe7, 0x9e, 0x18, 0x1e, 0x95, 0xe7, 0xce, 0x15, 0xc9, 0xc4,
	0x97, 0xf3, 0xc2, 0x7b, 0x12, 0x8f, 0x60, 0x84, 0x3f, 0xc8, 0x2a, 0x09, 0xfc, 0xc6, 0x3b, 0xae,
	0x89, 0x46, 0x53, 0x35, 0xef, 0xf2, 0xa5, 0xad, 0xe5, 0xc4, 0x37, 0xe1, 0x95, 0x0b, 0x5b, 0xa7,
	0xbf, 0x7a, 0x10, 0x9f, 0xa9, 0xee, 0xb8, 0xc2, 0xba, 0x14, 0x8f, 0x21, 0x52, 0xc6, 0x5c, 0x61,
	0x1c, 0x29, 0x63, 0x4e, 0xca, 0x3b, 0x80, 0xfa, 0x77, 0x00, 0xed, 0x40, 0x7c, 0x0b, 0xdf, 0x98,
	0x42, 0xe8, 0x06, 0xa1, 0xe1, 0x2d, 0x42, 0x3b, 0x10, 0x17, 0xba, 0x44, 0x6e, 0x6d, 0x14, 0xc8,
	0xea, 0x12, 0x2f, 0x2c, 0x93, 0x9d, 0xbb, 0xa6, 0xf2, 0x96, 0x6c, 0x60, 0x17, 0xb3, 0x70, 0x4e,
	0x36, 0x6d, 0x20, 0x3a, 0x53, 0x5d, 0xd6, 0x1a, 0xb1, 0x0b, 0xb1, 0xb1, 0x7a, 0x55, 0x95, 0x68,
	0xd7, 0xbb, 0x5f, 0xfb, 0xd7, 0xd7, 0xd6, 0xbf, 0xb9, 0xb6, 0x29, 0x24, 0xee, 0x96, 0x38, 0x1f,
	0x37, 0x3c, 0x39, 0xdc, 0x9e, 0x86, 0xeb, 0x9a, 0xae, 0x71, 0x64, 0xb1, 0x09, 0x56, 0x3a, 0x83,
	0xe4, 0x94, 0x91, 0xdd, 0x7b, 0x6f, 0xff, 0xae, 0xf9, 0x10, 0x06, 0x56, 0x7d, 0x0f, 0x78, 0x9c,
	0x99, 0x1e, 0x6d, 0xb2, 0xb6, 0x46, 0x3c, 0x81, 0xc8, 0x62, 0xbb, 0xac, 0x29, 0xa4, 0x0c, 0xde,
	0xfd, 0xf0, 0xd3, 0xd7, 0x10, 0x7f, 0x5a, 0xa2, 0xe5, 0xde, 0xee, 0xbd, 0xe5, 0x74, 0x05, 0x13,
	0x5f, 0xf4, 0x68, 0x85, 0x0d, 0x89, 0xff, 0xa1, 0xbf, 0x99, 0xa2, 0x5f, 0x95, 0xe2, 0x39, 0x24,
	0x54, 0x2d, 0xb0, 0x25, 0xb5, 0x30, 0x5c, 0x6b, 0x90, 0x5d, 0x09, 0x42, 0xc0, 0xb0, 0x51, 0x0b,
	0x0c, 0x69, 0xd9, 0x16, 0xaf, 0x60, 0x58, 0x2a, 0x52, 0xbc, 0xdb, 0x1b, 0x18, 0x75, 0x4b, 0x1f,
	0x15, 0xa9, 0x8c, 0xc3, 0xe9, 0x5b, 0x88, 0xd7, 0x8a, 0x43, 0xe1, 0x36, 0xee, 0xab, 0x3a, 0xd3,
	0x25, 0xbe, 0xd4, 0x65, 0x17, 0xa6, 0x63, 0xfb, 0xf0, 0x67, 0x0f, 0xe0, 0x4c, 0x75, 0xe7, 0x68,
	0x57, 0x55, 0x81, 0xe2, 0x00, 0x22, 0xff, 0x9f, 0x17, 0x62, 0x53, 0x63, 0xf3, 0x11, 0xd8, 0x7d,
	0x70, 0x7d, 0x7d, 0x59, 0x6b, 0xd2, 0xff, 0xc4, 0x21, 0x44, 0x7e, 0xd2, 0x6b, 0x0f, 0x36, 0x5b,
	0xdc, 0xbd, 0xa3, 0xf1, 0x9b, 0x37, 0x30, 0x62, 0x96, 0xe2, 0x6a, 0x8e, 0x35, 0xdb, 0xbf, 0x94,
	0xb8, 0x8c, 0xf8, 0xc3, 0xf4, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xfa, 0x2f, 0x6f,
	0xad, 0x04, 0x00, 0x00,
}
