// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_srv/user.proto

package user_srv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Openid               string   `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6c86a44bdc4ef92b, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *LoginReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type LoginRsq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsq) Reset()         { *m = LoginRsq{} }
func (m *LoginRsq) String() string { return proto.CompactTextString(m) }
func (*LoginRsq) ProtoMessage()    {}
func (*LoginRsq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6c86a44bdc4ef92b, []int{1}
}
func (m *LoginRsq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsq.Unmarshal(m, b)
}
func (m *LoginRsq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsq.Marshal(b, m, deterministic)
}
func (dst *LoginRsq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsq.Merge(dst, src)
}
func (m *LoginRsq) XXX_Size() int {
	return xxx_messageInfo_LoginRsq.Size(m)
}
func (m *LoginRsq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsq proto.InternalMessageInfo

func (m *LoginRsq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "user_srv.LoginReq")
	proto.RegisterType((*LoginRsq)(nil), "user_srv.LoginRsq")
}

func init() { proto.RegisterFile("user_srv/user.proto", fileDescriptor_user_6c86a44bdc4ef92b) }

var fileDescriptor_user_6c86a44bdc4ef92b = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x2e, 0x2a, 0xd3, 0x07, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x82, 0x4a, 0x89, 0x5c, 0x1c, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x41, 0xa9, 0x85, 0x42, 0x52, 0x5c,
	0x1c, 0x05, 0x39, 0x89, 0x25, 0x69, 0xf9, 0x45, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x70, 0xbe, 0x90, 0x18, 0x17, 0x5b, 0x7e, 0x41, 0x6a, 0x5e, 0x66, 0x8a, 0x04, 0x13, 0x58, 0x06,
	0xca, 0x13, 0x52, 0xe4, 0xe2, 0x49, 0x4c, 0x4e, 0x4e, 0x2d, 0x2e, 0x8e, 0x2f, 0xc9, 0xcf, 0x4e,
	0xcd, 0x93, 0x60, 0x06, 0xcb, 0x72, 0x43, 0xc4, 0x42, 0x40, 0x42, 0x4a, 0x32, 0x30, 0x2b, 0x8a,
	0x0b, 0x85, 0x04, 0xb8, 0x98, 0x4b, 0x33, 0x53, 0xc0, 0xa6, 0x33, 0x07, 0x81, 0x98, 0x46, 0x0e,
	0x5c, 0xdc, 0xa1, 0xc5, 0xa9, 0x45, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x86, 0x5c,
	0xac, 0x60, 0xc5, 0x42, 0x42, 0x7a, 0x30, 0x37, 0xea, 0xc1, 0x1c, 0x28, 0x85, 0x21, 0x56, 0x5c,
	0xa8, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x44, 0x1a, 0x87,
	0x9f, 0xea, 0x00, 0x00, 0x00,
}
