// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_srv/user.proto

package user_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *LoginReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type LoginRsq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsq) Reset()         { *m = LoginRsq{} }
func (m *LoginRsq) String() string { return proto.CompactTextString(m) }
func (*LoginRsq) ProtoMessage()    {}
func (*LoginRsq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{1}
}

func (m *LoginRsq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsq.Unmarshal(m, b)
}
func (m *LoginRsq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsq.Marshal(b, m, deterministic)
}
func (m *LoginRsq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsq.Merge(m, src)
}
func (m *LoginRsq) XXX_Size() int {
	return xxx_messageInfo_LoginRsq.Size(m)
}
func (m *LoginRsq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsq proto.InternalMessageInfo

func (m *LoginRsq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{2}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserRsq struct {
	Userinfo             *Userinfo `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserRsq) Reset()         { *m = UserRsq{} }
func (m *UserRsq) String() string { return proto.CompactTextString(m) }
func (*UserRsq) ProtoMessage()    {}
func (*UserRsq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{3}
}

func (m *UserRsq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRsq.Unmarshal(m, b)
}
func (m *UserRsq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRsq.Marshal(b, m, deterministic)
}
func (m *UserRsq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRsq.Merge(m, src)
}
func (m *UserRsq) XXX_Size() int {
	return xxx_messageInfo_UserRsq.Size(m)
}
func (m *UserRsq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRsq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRsq proto.InternalMessageInfo

func (m *UserRsq) GetUserinfo() *Userinfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type Userinfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Userinfo) Reset()         { *m = Userinfo{} }
func (m *Userinfo) String() string { return proto.CompactTextString(m) }
func (*Userinfo) ProtoMessage()    {}
func (*Userinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{4}
}

func (m *Userinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Userinfo.Unmarshal(m, b)
}
func (m *Userinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Userinfo.Marshal(b, m, deterministic)
}
func (m *Userinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Userinfo.Merge(m, src)
}
func (m *Userinfo) XXX_Size() int {
	return xxx_messageInfo_Userinfo.Size(m)
}
func (m *Userinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Userinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Userinfo proto.InternalMessageInfo

func (m *Userinfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Userinfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Userinfo) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Userinfo) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Userinfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Userinfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Userinfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Userinfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreateReq struct {
	Userinfo             *Userinfo   `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	LoginList            []*LoginReq `protobuf:"bytes,2,rep,name=login_list,json=loginList,proto3" json:"login_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d914a4924265a, []int{5}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetUserinfo() *Userinfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

func (m *CreateReq) GetLoginList() []*LoginReq {
	if m != nil {
		return m.LoginList
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "user_srv.LoginReq")
	proto.RegisterType((*LoginRsq)(nil), "user_srv.LoginRsq")
	proto.RegisterType((*UserReq)(nil), "user_srv.UserReq")
	proto.RegisterType((*UserRsq)(nil), "user_srv.UserRsq")
	proto.RegisterType((*Userinfo)(nil), "user_srv.Userinfo")
	proto.RegisterType((*CreateReq)(nil), "user_srv.CreateReq")
}

func init() { proto.RegisterFile("user_srv/user.proto", fileDescriptor_be3d914a4924265a) }

var fileDescriptor_be3d914a4924265a = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x37, 0x04, 0x42, 0x32, 0xec, 0x61, 0x77, 0x90, 0x56, 0x11, 0xb0, 0x12, 0x9b, 0xd3,
	0x9e, 0xb2, 0x82, 0x3d, 0xf5, 0x88, 0x7a, 0xaa, 0xc4, 0x29, 0x2d, 0xe7, 0xc8, 0x4d, 0x1c, 0x64,
	0x11, 0x1c, 0x62, 0x1b, 0x9e, 0xa8, 0x0f, 0xd6, 0x47, 0xa9, 0x6c, 0xc7, 0x20, 0x0a, 0x97, 0xde,
	0x32, 0xdf, 0x37, 0x63, 0xfb, 0x77, 0x0c, 0xe3, 0xa3, 0xa4, 0x22, 0x97, 0xe2, 0xf4, 0x4f, 0x7f,
	0xa4, 0x07, 0xd1, 0xa8, 0x06, 0x43, 0x07, 0x93, 0x0a, 0xc2, 0x75, 0xb3, 0x65, 0x3c, 0xa3, 0x2d,
	0x4e, 0x20, 0x3c, 0xd4, 0x44, 0x55, 0x8d, 0xd8, 0xc7, 0xde, 0xdc, 0xfb, 0x1b, 0x65, 0xe7, 0x1a,
	0xa7, 0x10, 0x15, 0x35, 0xa3, 0x5c, 0xe5, 0xac, 0x8c, 0x7b, 0x56, 0x5a, 0xf0, 0x54, 0xe2, 0x1f,
	0xf8, 0x4e, 0x8a, 0x82, 0x4a, 0x99, 0xab, 0x66, 0x47, 0x79, 0xec, 0x1b, 0x3f, 0xb2, 0xec, 0x45,
	0xa3, 0x64, 0xe6, 0xf6, 0x91, 0x2d, 0xfe, 0x00, 0xff, 0xc8, 0x4a, 0xb3, 0x85, 0x9f, 0xe9, 0xcf,
	0x64, 0x0a, 0xc3, 0x8d, 0xa4, 0x42, 0x1f, 0xe2, 0x56, 0x3e, 0x74, 0x52, 0xb6, 0x98, 0x82, 0x39,
	0x39, 0xe3, 0x55, 0x63, 0x3a, 0x46, 0x4b, 0x4c, 0x5d, 0x94, 0x74, 0xd3, 0x99, 0xec, 0xdc, 0x93,
	0xbc, 0x7b, 0x10, 0x3a, 0x7c, 0xbb, 0xb2, 0x0e, 0xcc, 0x59, 0xb1, 0xe3, 0x64, 0x4f, 0x5d, 0x26,
	0x57, 0xe3, 0x0c, 0xa2, 0x8a, 0x09, 0xa9, 0x8c, 0xb4, 0x81, 0x2e, 0x40, 0x4f, 0xd6, 0xa4, 0x93,
	0x7d, 0x3b, 0xe9, 0x6a, 0xfc, 0x05, 0xc1, 0x96, 0xf2, 0x92, 0x8a, 0x78, 0x60, 0x4c, 0x57, 0x69,
	0x4e, 0x4e, 0x44, 0x11, 0x11, 0x07, 0x96, 0xdb, 0x0a, 0x7f, 0x03, 0x1c, 0x0f, 0x25, 0x51, 0xb4,
	0xcc, 0x89, 0x8a, 0x87, 0x76, 0xab, 0x8e, 0xac, 0x94, 0xd6, 0x85, 0xa0, 0x4e, 0x87, 0x56, 0x77,
	0x64, 0xa5, 0x12, 0x0e, 0xd1, 0xa3, 0x29, 0xf4, 0xe5, 0x7d, 0xf1, 0x7e, 0x70, 0x01, 0x50, 0xeb,
	0xbf, 0x92, 0xd7, 0x4c, 0xaa, 0xb8, 0x37, 0xf7, 0xaf, 0x27, 0xdc, 0xcb, 0xc8, 0x22, 0xd3, 0xb5,
	0x66, 0x52, 0x2d, 0xdf, 0x3c, 0x18, 0xe9, 0x95, 0x9e, 0xa9, 0x38, 0xb1, 0x82, 0xe2, 0x02, 0x06,
	0xa6, 0x0d, 0xef, 0xcc, 0x4d, 0x6e, 0x98, 0x6c, 0x93, 0x6f, 0x98, 0x42, 0x5f, 0xaf, 0x80, 0x3f,
	0xaf, 0xcf, 0xa6, 0x07, 0x3e, 0x23, 0xd3, 0xbf, 0x84, 0xc0, 0x46, 0xc4, 0xf1, 0x45, 0x9f, 0x43,
	0xdf, 0x9d, 0x79, 0x0d, 0xcc, 0x43, 0xff, 0xff, 0x11, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x90, 0xac,
	0x62, 0xff, 0x02, 0x00, 0x00,
}
