// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usersrv/user.proto

/*
Package usersrv is a generated protocol buffer package.

It is generated from these files:
	usersrv/user.proto

It has these top-level messages:
	LoginByPasswordReq
	LoginByCaptchaReq
	LoginByOAuthReq
	AuthRsp
	UserReq
	UerRsp
	UserRsp
	BindReq
	UnbindReq
	UpdateReq
*/
package usersrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// 手机号密码登陆
	LoginByPassword(ctx context.Context, in *LoginByPasswordReq, opts ...client.CallOption) (*AuthRsp, error)
	// 短信验证码登陆
	LoginByCaptcha(ctx context.Context, in *LoginByCaptchaReq, opts ...client.CallOption) (*AuthRsp, error)
	// 第三方授权登陆
	LoginByOAuth(ctx context.Context, in *LoginByOAuthReq, opts ...client.CallOption) (*AuthRsp, error)
	// 创建用户
	// rpc Register(RegisterReq) returns (AuthRsp) {}
	// 绑定用户
	Bind(ctx context.Context, in *BindReq, opts ...client.CallOption) (*UserRsp, error)
	// //解绑用户
	Unbind(ctx context.Context, in *UnbindReq, opts ...client.CallOption) (*UserRsp, error)
	// 用户信息
	User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserRsp, error)
	// 更新用户信息
	Update(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*UserRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "usersrv"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) LoginByPassword(ctx context.Context, in *LoginByPasswordReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginByPassword", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginByCaptcha(ctx context.Context, in *LoginByCaptchaReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginByCaptcha", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginByOAuth(ctx context.Context, in *LoginByOAuthReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginByOAuth", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Bind(ctx context.Context, in *BindReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.Bind", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Unbind(ctx context.Context, in *UnbindReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.Unbind", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.User", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UpdateReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.Update", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 手机号密码登陆
	LoginByPassword(context.Context, *LoginByPasswordReq, *AuthRsp) error
	// 短信验证码登陆
	LoginByCaptcha(context.Context, *LoginByCaptchaReq, *AuthRsp) error
	// 第三方授权登陆
	LoginByOAuth(context.Context, *LoginByOAuthReq, *AuthRsp) error
	// 创建用户
	// rpc Register(RegisterReq) returns (AuthRsp) {}
	// 绑定用户
	Bind(context.Context, *BindReq, *UserRsp) error
	// //解绑用户
	Unbind(context.Context, *UnbindReq, *UserRsp) error
	// 用户信息
	User(context.Context, *UserReq, *UserRsp) error
	// 更新用户信息
	Update(context.Context, *UpdateReq, *UserRsp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	type userService interface {
		LoginByPassword(ctx context.Context, in *LoginByPasswordReq, out *AuthRsp) error
		LoginByCaptcha(ctx context.Context, in *LoginByCaptchaReq, out *AuthRsp) error
		LoginByOAuth(ctx context.Context, in *LoginByOAuthReq, out *AuthRsp) error
		Bind(ctx context.Context, in *BindReq, out *UserRsp) error
		Unbind(ctx context.Context, in *UnbindReq, out *UserRsp) error
		User(ctx context.Context, in *UserReq, out *UserRsp) error
		Update(ctx context.Context, in *UpdateReq, out *UserRsp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) LoginByPassword(ctx context.Context, in *LoginByPasswordReq, out *AuthRsp) error {
	return h.UserServiceHandler.LoginByPassword(ctx, in, out)
}

func (h *userServiceHandler) LoginByCaptcha(ctx context.Context, in *LoginByCaptchaReq, out *AuthRsp) error {
	return h.UserServiceHandler.LoginByCaptcha(ctx, in, out)
}

func (h *userServiceHandler) LoginByOAuth(ctx context.Context, in *LoginByOAuthReq, out *AuthRsp) error {
	return h.UserServiceHandler.LoginByOAuth(ctx, in, out)
}

func (h *userServiceHandler) Bind(ctx context.Context, in *BindReq, out *UserRsp) error {
	return h.UserServiceHandler.Bind(ctx, in, out)
}

func (h *userServiceHandler) Unbind(ctx context.Context, in *UnbindReq, out *UserRsp) error {
	return h.UserServiceHandler.Unbind(ctx, in, out)
}

func (h *userServiceHandler) User(ctx context.Context, in *UserReq, out *UserRsp) error {
	return h.UserServiceHandler.User(ctx, in, out)
}

func (h *userServiceHandler) Update(ctx context.Context, in *UpdateReq, out *UserRsp) error {
	return h.UserServiceHandler.Update(ctx, in, out)
}
