// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usersrv/user.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//权限信息
type AuthRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRsp) Reset()         { *m = AuthRsp{} }
func (m *AuthRsp) String() string { return proto.CompactTextString(m) }
func (*AuthRsp) ProtoMessage()    {}
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{0}
}

func (m *AuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRsp.Unmarshal(m, b)
}
func (m *AuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRsp.Marshal(b, m, deterministic)
}
func (m *AuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRsp.Merge(m, src)
}
func (m *AuthRsp) XXX_Size() int {
	return xxx_messageInfo_AuthRsp.Size(m)
}
func (m *AuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRsp proto.InternalMessageInfo

func (m *AuthRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRsp) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *AuthRsp) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//手机号+密码登陆
type SigninReq struct {
	Loginname            string   `protobuf:"bytes,1,opt,name=loginname,proto3" json:"loginname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninReq) Reset()         { *m = SigninReq{} }
func (m *SigninReq) String() string { return proto.CompactTextString(m) }
func (*SigninReq) ProtoMessage()    {}
func (*SigninReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{1}
}

func (m *SigninReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninReq.Unmarshal(m, b)
}
func (m *SigninReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninReq.Marshal(b, m, deterministic)
}
func (m *SigninReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninReq.Merge(m, src)
}
func (m *SigninReq) XXX_Size() int {
	return xxx_messageInfo_SigninReq.Size(m)
}
func (m *SigninReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninReq.DiscardUnknown(m)
}

var xxx_messageInfo_SigninReq proto.InternalMessageInfo

func (m *SigninReq) GetLoginname() string {
	if m != nil {
		return m.Loginname
	}
	return ""
}

func (m *SigninReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//SignupReq 普通注册
type SignupReq struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupReq) Reset()         { *m = SignupReq{} }
func (m *SignupReq) String() string { return proto.CompactTextString(m) }
func (*SignupReq) ProtoMessage()    {}
func (*SignupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{2}
}

func (m *SignupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReq.Unmarshal(m, b)
}
func (m *SignupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReq.Marshal(b, m, deterministic)
}
func (m *SignupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReq.Merge(m, src)
}
func (m *SignupReq) XXX_Size() int {
	return xxx_messageInfo_SignupReq.Size(m)
}
func (m *SignupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReq proto.InternalMessageInfo

func (m *SignupReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SignupReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *SignupReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *SignupReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignupReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//用户信息 profile
type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *UserInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

//手机号+验证码登陆
type SigninByPhoneCaptchaReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Captcha              string   `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	CaptchaId            int64    `protobuf:"varint,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninByPhoneCaptchaReq) Reset()         { *m = SigninByPhoneCaptchaReq{} }
func (m *SigninByPhoneCaptchaReq) String() string { return proto.CompactTextString(m) }
func (*SigninByPhoneCaptchaReq) ProtoMessage()    {}
func (*SigninByPhoneCaptchaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{4}
}

func (m *SigninByPhoneCaptchaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Unmarshal(m, b)
}
func (m *SigninByPhoneCaptchaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Marshal(b, m, deterministic)
}
func (m *SigninByPhoneCaptchaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninByPhoneCaptchaReq.Merge(m, src)
}
func (m *SigninByPhoneCaptchaReq) XXX_Size() int {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Size(m)
}
func (m *SigninByPhoneCaptchaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninByPhoneCaptchaReq.DiscardUnknown(m)
}

var xxx_messageInfo_SigninByPhoneCaptchaReq proto.InternalMessageInfo

func (m *SigninByPhoneCaptchaReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SigninByPhoneCaptchaReq) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *SigninByPhoneCaptchaReq) GetCaptchaId() int64 {
	if m != nil {
		return m.CaptchaId
	}
	return 0
}

//第三方授权登陆
type OAuthAuthorizeReq struct {
	Platform             string            `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Appid                string            `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Sercet               string            `protobuf:"bytes,3,opt,name=sercet,proto3" json:"sercet,omitempty"`
	Code                 string            `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Ref                  string            `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	Fileds               map[string]string `protobuf:"bytes,6,rep,name=fileds,proto3" json:"fileds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OAuthAuthorizeReq) Reset()         { *m = OAuthAuthorizeReq{} }
func (m *OAuthAuthorizeReq) String() string { return proto.CompactTextString(m) }
func (*OAuthAuthorizeReq) ProtoMessage()    {}
func (*OAuthAuthorizeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{5}
}

func (m *OAuthAuthorizeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthAuthorizeReq.Unmarshal(m, b)
}
func (m *OAuthAuthorizeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthAuthorizeReq.Marshal(b, m, deterministic)
}
func (m *OAuthAuthorizeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthAuthorizeReq.Merge(m, src)
}
func (m *OAuthAuthorizeReq) XXX_Size() int {
	return xxx_messageInfo_OAuthAuthorizeReq.Size(m)
}
func (m *OAuthAuthorizeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthAuthorizeReq.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthAuthorizeReq proto.InternalMessageInfo

func (m *OAuthAuthorizeReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *OAuthAuthorizeReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *OAuthAuthorizeReq) GetSercet() string {
	if m != nil {
		return m.Sercet
	}
	return ""
}

func (m *OAuthAuthorizeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OAuthAuthorizeReq) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *OAuthAuthorizeReq) GetFileds() map[string]string {
	if m != nil {
		return m.Fileds
	}
	return nil
}

type OAuthAuthorizeRsp struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthAuthorizeRsp) Reset()         { *m = OAuthAuthorizeRsp{} }
func (m *OAuthAuthorizeRsp) String() string { return proto.CompactTextString(m) }
func (*OAuthAuthorizeRsp) ProtoMessage()    {}
func (*OAuthAuthorizeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{6}
}

func (m *OAuthAuthorizeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthAuthorizeRsp.Unmarshal(m, b)
}
func (m *OAuthAuthorizeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthAuthorizeRsp.Marshal(b, m, deterministic)
}
func (m *OAuthAuthorizeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthAuthorizeRsp.Merge(m, src)
}
func (m *OAuthAuthorizeRsp) XXX_Size() int {
	return xxx_messageInfo_OAuthAuthorizeRsp.Size(m)
}
func (m *OAuthAuthorizeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthAuthorizeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthAuthorizeRsp proto.InternalMessageInfo

func (m *OAuthAuthorizeRsp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//第三方授权登陆
type OAuthCallbackReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthCallbackReq) Reset()         { *m = OAuthCallbackReq{} }
func (m *OAuthCallbackReq) String() string { return proto.CompactTextString(m) }
func (*OAuthCallbackReq) ProtoMessage()    {}
func (*OAuthCallbackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{7}
}

func (m *OAuthCallbackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthCallbackReq.Unmarshal(m, b)
}
func (m *OAuthCallbackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthCallbackReq.Marshal(b, m, deterministic)
}
func (m *OAuthCallbackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthCallbackReq.Merge(m, src)
}
func (m *OAuthCallbackReq) XXX_Size() int {
	return xxx_messageInfo_OAuthCallbackReq.Size(m)
}
func (m *OAuthCallbackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthCallbackReq.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthCallbackReq proto.InternalMessageInfo

func (m *OAuthCallbackReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OAuthCallbackReq) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRsp)(nil), "usersrv.AuthRsp")
	proto.RegisterType((*SigninReq)(nil), "usersrv.SigninReq")
	proto.RegisterType((*SignupReq)(nil), "usersrv.SignupReq")
	proto.RegisterType((*UserInfo)(nil), "usersrv.UserInfo")
	proto.RegisterType((*SigninByPhoneCaptchaReq)(nil), "usersrv.SigninByPhoneCaptchaReq")
	proto.RegisterType((*OAuthAuthorizeReq)(nil), "usersrv.OAuthAuthorizeReq")
	proto.RegisterMapType((map[string]string)(nil), "usersrv.OAuthAuthorizeReq.FiledsEntry")
	proto.RegisterType((*OAuthAuthorizeRsp)(nil), "usersrv.OAuthAuthorizeRsp")
	proto.RegisterType((*OAuthCallbackReq)(nil), "usersrv.OAuthCallbackReq")
}

func init() { proto.RegisterFile("usersrv/user.proto", fileDescriptor_e67c0fc7414e723c) }

var fileDescriptor_e67c0fc7414e723c = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0xdd, 0xb4, 0xdb, 0xb4, 0xf9, 0x0a, 0xd2, 0x1d, 0xca, 0x1a, 0x82, 0x42, 0x09, 0x28, 0xbd,
	0xaa, 0xba, 0xde, 0xa8, 0x88, 0x50, 0xcb, 0x0a, 0x2b, 0x82, 0x92, 0xc5, 0xeb, 0x65, 0x36, 0x99,
	0xb6, 0xa1, 0xe9, 0x64, 0x9c, 0x4c, 0x2a, 0xf5, 0x19, 0x7c, 0x07, 0xdf, 0xcf, 0x87, 0x10, 0x99,
	0xdf, 0xa6, 0xed, 0xf6, 0xa2, 0xf4, 0x3b, 0x67, 0x66, 0x4e, 0xce, 0xf7, 0xe5, 0x4c, 0x00, 0xd5,
	0x15, 0xe1, 0x15, 0xdf, 0xbc, 0x90, 0xff, 0x13, 0xc6, 0x4b, 0x51, 0xa2, 0xae, 0xe1, 0xe2, 0x19,
	0x74, 0xa7, 0xb5, 0x58, 0x26, 0x15, 0x43, 0x43, 0xe8, 0x88, 0x72, 0x45, 0x68, 0xe8, 0x8d, 0xbc,
	0x71, 0x90, 0x68, 0x80, 0x06, 0xd0, 0xe6, 0x64, 0x1e, 0xb6, 0x14, 0x27, 0x4b, 0xc9, 0xd4, 0x79,
	0x16, 0xb6, 0x47, 0xde, 0xb8, 0x9d, 0xc8, 0x32, 0xbe, 0x86, 0xe0, 0x36, 0x5f, 0xd0, 0x9c, 0x26,
	0xe4, 0x07, 0x7a, 0x02, 0x41, 0x51, 0x2e, 0x72, 0x4a, 0xf1, 0x9a, 0x18, 0xa9, 0x1d, 0x81, 0x22,
	0xe8, 0x31, 0x5c, 0x55, 0x3f, 0x4b, 0x9e, 0x19, 0x4d, 0x87, 0xe3, 0x3f, 0x9e, 0xd6, 0xa9, 0x99,
	0xd4, 0x89, 0xa0, 0x47, 0xf3, 0x74, 0xd5, 0x90, 0x71, 0x18, 0x5d, 0x82, 0xbf, 0x20, 0x34, 0x23,
	0xdc, 0x68, 0x18, 0x24, 0x79, 0xbc, 0xc1, 0x02, 0x73, 0xe5, 0x2e, 0x48, 0x0c, 0x92, 0xad, 0x91,
	0x35, 0xce, 0x8b, 0xf0, 0x5c, 0xb7, 0xa6, 0x80, 0x64, 0xd9, 0xb2, 0xa4, 0x24, 0xec, 0x68, 0x56,
	0x81, 0x3d, 0x87, 0xfe, 0x81, 0xc3, 0xbf, 0x1e, 0xf4, 0xbe, 0x57, 0x84, 0xdf, 0xd0, 0x79, 0x69,
	0xe7, 0xe0, 0xb9, 0x39, 0xec, 0x59, 0x6e, 0x9d, 0xb4, 0xdc, 0x3e, 0x61, 0xf9, 0x7c, 0xcf, 0xf2,
	0x25, 0xf8, 0x95, 0xc0, 0xa2, 0xae, 0x94, 0xbb, 0x4e, 0x62, 0x10, 0x7a, 0x0a, 0x50, 0xb3, 0x0c,
	0x0b, 0x92, 0xdd, 0x61, 0x61, 0x0c, 0x06, 0x86, 0x99, 0x0a, 0xb9, 0x9c, 0x72, 0x62, 0x97, 0xbb,
	0x7a, 0xd9, 0x30, 0x53, 0xb1, 0x6b, 0xb9, 0xd7, 0x6c, 0xd9, 0x8d, 0x27, 0x68, 0x8c, 0x27, 0x5e,
	0xc2, 0x63, 0xfd, 0x56, 0x3f, 0x6e, 0xbf, 0xc9, 0x6d, 0x33, 0xcc, 0x44, 0xba, 0xc4, 0xf2, 0xdd,
	0x38, 0x19, 0xaf, 0x29, 0x13, 0x42, 0x37, 0xd5, 0x7b, 0x4c, 0xf7, 0x16, 0x2a, 0x57, 0xba, 0xbc,
	0x73, 0xc9, 0x09, 0x0c, 0x73, 0x93, 0xc5, 0xff, 0x3c, 0xb8, 0xf8, 0x2a, 0x63, 0x28, 0x7f, 0x25,
	0xcf, 0x7f, 0x11, 0x13, 0x00, 0x56, 0x60, 0x31, 0x2f, 0xf9, 0xda, 0x06, 0xc0, 0x62, 0x69, 0x00,
	0x33, 0x96, 0xdb, 0x0c, 0x69, 0xa0, 0x66, 0x46, 0x78, 0x4a, 0x84, 0x9d, 0xb1, 0x46, 0x08, 0xc1,
	0x79, 0x5a, 0x66, 0xc4, 0x4c, 0x58, 0xd5, 0x36, 0xd7, 0x9d, 0x5d, 0xae, 0x3f, 0x80, 0x3f, 0xcf,
	0x0b, 0x92, 0x55, 0xa1, 0x3f, 0x6a, 0x8f, 0xfb, 0x57, 0xcf, 0x27, 0xe6, 0x92, 0x4c, 0x8e, 0xbc,
	0x4d, 0x3e, 0xa9, 0x8d, 0xd7, 0x54, 0xf0, 0x6d, 0x62, 0x4e, 0x45, 0x6f, 0xa1, 0xdf, 0xa0, 0xe5,
	0x03, 0x56, 0x64, 0x6b, 0x9c, 0xcb, 0x52, 0x9a, 0xde, 0xe0, 0xa2, 0xb6, 0xd9, 0xd0, 0xe0, 0x5d,
	0xeb, 0x8d, 0x17, 0x3f, 0x3b, 0xea, 0xbf, 0x62, 0x2a, 0x5f, 0xbc, 0xb0, 0x02, 0x35, 0x2f, 0xe2,
	0xf7, 0x30, 0x50, 0xdb, 0x66, 0xb8, 0x28, 0xee, 0x71, 0xba, 0x92, 0x53, 0xb2, 0xbd, 0x79, 0x8d,
	0xde, 0x86, 0xd0, 0x91, 0x69, 0x71, 0x0f, 0x52, 0xe0, 0xea, 0x77, 0x0b, 0xfa, 0x32, 0xbc, 0xb7,
	0x84, 0x6f, 0xf2, 0x94, 0xa0, 0x57, 0xe0, 0xeb, 0xdb, 0x86, 0x90, 0xeb, 0xd4, 0x5d, 0xbf, 0xe8,
	0xc2, 0x71, 0x36, 0xf0, 0xf1, 0x19, 0x7a, 0xa9, 0x8f, 0xe4, 0xf4, 0xe0, 0x88, 0xba, 0xf9, 0xd1,
	0xc0, 0x71, 0xe6, 0x93, 0x12, 0x9f, 0xa1, 0x2f, 0x30, 0x7c, 0x28, 0x44, 0x68, 0x74, 0x70, 0xfe,
	0x28, 0x63, 0x0f, 0xaa, 0x7d, 0x86, 0x47, 0xfb, 0x73, 0x42, 0xd1, 0xe9, 0x97, 0x14, 0x9d, 0x5c,
	0x93, 0x5a, 0xf7, 0xbe, 0xfa, 0x12, 0xbe, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x36, 0x34,
	0x83, 0x1f, 0x05, 0x00, 0x00,
}
