// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usersrv/user.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//权限信息
type AuthRsp struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  int64             `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Fileds               map[string]string `protobuf:"bytes,3,rep,name=fileds,proto3" json:"fileds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthRsp) Reset()         { *m = AuthRsp{} }
func (m *AuthRsp) String() string { return proto.CompactTextString(m) }
func (*AuthRsp) ProtoMessage()    {}
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{0}
}

func (m *AuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRsp.Unmarshal(m, b)
}
func (m *AuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRsp.Marshal(b, m, deterministic)
}
func (m *AuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRsp.Merge(m, src)
}
func (m *AuthRsp) XXX_Size() int {
	return xxx_messageInfo_AuthRsp.Size(m)
}
func (m *AuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRsp proto.InternalMessageInfo

func (m *AuthRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRsp) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuthRsp) GetFileds() map[string]string {
	if m != nil {
		return m.Fileds
	}
	return nil
}

//手机号+密码登陆
type SigninReq struct {
	Loginname            string   `protobuf:"bytes,1,opt,name=loginname,proto3" json:"loginname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninReq) Reset()         { *m = SigninReq{} }
func (m *SigninReq) String() string { return proto.CompactTextString(m) }
func (*SigninReq) ProtoMessage()    {}
func (*SigninReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{1}
}

func (m *SigninReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninReq.Unmarshal(m, b)
}
func (m *SigninReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninReq.Marshal(b, m, deterministic)
}
func (m *SigninReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninReq.Merge(m, src)
}
func (m *SigninReq) XXX_Size() int {
	return xxx_messageInfo_SigninReq.Size(m)
}
func (m *SigninReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninReq.DiscardUnknown(m)
}

var xxx_messageInfo_SigninReq proto.InternalMessageInfo

func (m *SigninReq) GetLoginname() string {
	if m != nil {
		return m.Loginname
	}
	return ""
}

func (m *SigninReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//SignupReq 普通注册
type SignupReq struct {
	Userinfo             *UserInfo `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignupReq) Reset()         { *m = SignupReq{} }
func (m *SignupReq) String() string { return proto.CompactTextString(m) }
func (*SignupReq) ProtoMessage()    {}
func (*SignupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{2}
}

func (m *SignupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReq.Unmarshal(m, b)
}
func (m *SignupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReq.Marshal(b, m, deterministic)
}
func (m *SignupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReq.Merge(m, src)
}
func (m *SignupReq) XXX_Size() int {
	return xxx_messageInfo_SignupReq.Size(m)
}
func (m *SignupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReq proto.InternalMessageInfo

func (m *SignupReq) GetUserinfo() *UserInfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

//用户信息 profile
type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *UserInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

//手机号+验证码登陆
type SigninByPhoneCaptchaReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Captcha              string   `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	CaptchaId            int64    `protobuf:"varint,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninByPhoneCaptchaReq) Reset()         { *m = SigninByPhoneCaptchaReq{} }
func (m *SigninByPhoneCaptchaReq) String() string { return proto.CompactTextString(m) }
func (*SigninByPhoneCaptchaReq) ProtoMessage()    {}
func (*SigninByPhoneCaptchaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67c0fc7414e723c, []int{4}
}

func (m *SigninByPhoneCaptchaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Unmarshal(m, b)
}
func (m *SigninByPhoneCaptchaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Marshal(b, m, deterministic)
}
func (m *SigninByPhoneCaptchaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninByPhoneCaptchaReq.Merge(m, src)
}
func (m *SigninByPhoneCaptchaReq) XXX_Size() int {
	return xxx_messageInfo_SigninByPhoneCaptchaReq.Size(m)
}
func (m *SigninByPhoneCaptchaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninByPhoneCaptchaReq.DiscardUnknown(m)
}

var xxx_messageInfo_SigninByPhoneCaptchaReq proto.InternalMessageInfo

func (m *SigninByPhoneCaptchaReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SigninByPhoneCaptchaReq) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *SigninByPhoneCaptchaReq) GetCaptchaId() int64 {
	if m != nil {
		return m.CaptchaId
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRsp)(nil), "usersrv.AuthRsp")
	proto.RegisterMapType((map[string]string)(nil), "usersrv.AuthRsp.FiledsEntry")
	proto.RegisterType((*SigninReq)(nil), "usersrv.SigninReq")
	proto.RegisterType((*SignupReq)(nil), "usersrv.SignupReq")
	proto.RegisterType((*UserInfo)(nil), "usersrv.UserInfo")
	proto.RegisterType((*SigninByPhoneCaptchaReq)(nil), "usersrv.SigninByPhoneCaptchaReq")
}

func init() { proto.RegisterFile("usersrv/user.proto", fileDescriptor_e67c0fc7414e723c) }

var fileDescriptor_e67c0fc7414e723c = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xc5, 0x5d, 0xb2, 0xc9, 0x4e, 0x2e, 0xc5, 0x8a, 0xc0, 0x8a, 0x8a, 0xb4, 0xda, 0x53, 0x2e,
	0x04, 0x14, 0x38, 0x40, 0x6f, 0x01, 0x15, 0xa9, 0x12, 0x07, 0xe4, 0x88, 0x73, 0x65, 0xd6, 0x4e,
	0x62, 0x25, 0xb5, 0x8d, 0xd7, 0x1b, 0x94, 0xbf, 0xc3, 0x1f, 0xe1, 0x3f, 0xf0, 0x8b, 0x90, 0x3f,
	0x76, 0x5b, 0xa5, 0x39, 0xc5, 0xef, 0x8d, 0xe7, 0xcd, 0xbc, 0xe7, 0x2c, 0xe0, 0xb6, 0x11, 0xb6,
	0xb1, 0x87, 0xb7, 0xfe, 0x77, 0x6e, 0xac, 0x76, 0x1a, 0x0f, 0x13, 0x57, 0xfd, 0x41, 0x30, 0x5c,
	0xb6, 0x6e, 0x4b, 0x1b, 0x83, 0x27, 0x30, 0x70, 0x7a, 0x27, 0x14, 0x41, 0x25, 0x9a, 0x15, 0x34,
	0x02, 0x7c, 0x09, 0x59, 0x2b, 0x39, 0xb9, 0x28, 0xd1, 0x2c, 0xa3, 0xfe, 0x88, 0x3f, 0x40, 0xbe,
	0x96, 0x7b, 0xc1, 0x1b, 0x92, 0x95, 0xd9, 0x6c, 0xbc, 0xb8, 0x9a, 0x27, 0xb5, 0x79, 0x52, 0x9a,
	0x7f, 0x0d, 0xe5, 0x1b, 0xe5, 0xec, 0x91, 0xa6, 0xbb, 0xd3, 0x4f, 0x30, 0x7e, 0x44, 0x7b, 0xd9,
	0x9d, 0x38, 0xa6, 0x51, 0xfe, 0xe8, 0xc7, 0x1f, 0xd8, 0xbe, 0x15, 0x61, 0x54, 0x41, 0x23, 0xb8,
	0xbe, 0xf8, 0x88, 0xaa, 0x1b, 0x28, 0x56, 0x72, 0xa3, 0xa4, 0xa2, 0xe2, 0x17, 0xbe, 0x82, 0x62,
	0xaf, 0x37, 0x52, 0x29, 0x76, 0x2f, 0x52, 0xfb, 0x03, 0x81, 0xa7, 0x30, 0x32, 0xac, 0x69, 0x7e,
	0x6b, 0xcb, 0x93, 0x4e, 0x8f, 0xab, 0xeb, 0x28, 0xd3, 0x1a, 0x2f, 0xf3, 0x06, 0x46, 0x7e, 0x6b,
	0xa9, 0xd6, 0x3a, 0xa8, 0x8c, 0x17, 0x2f, 0x7a, 0x1b, 0x3f, 0x1a, 0x61, 0x6f, 0xd5, 0x5a, 0xd3,
	0xfe, 0x4a, 0xf5, 0x0f, 0xc1, 0xa8, 0xa3, 0xbb, 0x48, 0xd0, 0x43, 0x24, 0x13, 0x18, 0x98, 0xad,
	0x56, 0xfd, 0xee, 0x01, 0x78, 0x56, 0xdc, 0x33, 0xb9, 0x27, 0x59, 0x64, 0x03, 0xf0, 0x2b, 0x2a,
	0x59, 0xef, 0xc2, 0xfe, 0xcf, 0xe3, 0x8a, 0x1d, 0xc6, 0x2f, 0x21, 0xdf, 0x08, 0xc5, 0x85, 0x25,
	0x83, 0x12, 0xcd, 0x06, 0x34, 0x21, 0xcf, 0xb3, 0x03, 0x73, 0xcc, 0x92, 0x3c, 0x74, 0x24, 0x84,
	0x5f, 0x03, 0xb4, 0x86, 0x33, 0x27, 0xf8, 0x1d, 0x73, 0x64, 0x18, 0xd3, 0x48, 0xcc, 0xd2, 0xf9,
	0x72, 0x6d, 0x45, 0x57, 0x1e, 0xc5, 0x72, 0x62, 0x96, 0xae, 0xda, 0xc2, 0xab, 0x98, 0xeb, 0xe7,
	0xe3, 0x77, 0xbf, 0xf0, 0x17, 0x66, 0x5c, 0xbd, 0x65, 0x3e, 0x9e, 0xde, 0x10, 0x7a, 0x6c, 0x88,
	0xc0, 0xb0, 0x8e, 0x77, 0x92, 0xd1, 0x0e, 0x86, 0x49, 0xf1, 0x78, 0x27, 0x79, 0xf0, 0x9b, 0xd1,
	0x22, 0x31, 0xb7, 0x7c, 0xf1, 0x17, 0xc1, 0xd8, 0xc7, 0xb7, 0x12, 0xf6, 0x20, 0x6b, 0x81, 0xdf,
	0x41, 0xbe, 0x92, 0x6a, 0x23, 0x15, 0xc6, 0x7d, 0xea, 0xfd, 0x13, 0x4f, 0x2f, 0x4f, 0xff, 0x50,
	0xd5, 0xb3, 0xae, 0xa3, 0x35, 0x27, 0x1d, 0xe1, 0x35, 0xcf, 0x76, 0x7c, 0x83, 0xc9, 0x39, 0x77,
	0xb8, 0x3c, 0x99, 0xf8, 0xc4, 0xfc, 0x39, 0xb5, 0x9f, 0x79, 0xf8, 0x70, 0xde, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x25, 0xd0, 0xef, 0x23, 0x4e, 0x03, 0x00, 0x00,
}
