// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usersrv/user.proto

/*
Package usersrv is a generated protocol buffer package.

It is generated from these files:
	usersrv/user.proto

It has these top-level messages:
	LoginData
	SessionData
	UserData
	RegisterData
	BindData
	UnbindData
	UpdateData
*/
package usersrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// 密码登陆/验证码登陆/第三方权限登陆
	Login(ctx context.Context, in *LoginData, opts ...client.CallOption) (*SessionData, error)
	// 创建用户
	Register(ctx context.Context, in *RegisterData, opts ...client.CallOption) (*SessionData, error)
	// 绑定用户
	Bind(ctx context.Context, in *BindData, opts ...client.CallOption) (*UserData, error)
	// //解绑用户
	Unbind(ctx context.Context, in *UnbindData, opts ...client.CallOption) (*UserData, error)
	// 用户信息
	User(ctx context.Context, in *SessionData, opts ...client.CallOption) (*UserData, error)
	// 更新用户信息
	Update(ctx context.Context, in *UpdateData, opts ...client.CallOption) (*UserData, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "usersrv"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Login(ctx context.Context, in *LoginData, opts ...client.CallOption) (*SessionData, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(SessionData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Register(ctx context.Context, in *RegisterData, opts ...client.CallOption) (*SessionData, error) {
	req := c.c.NewRequest(c.name, "UserService.Register", in)
	out := new(SessionData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Bind(ctx context.Context, in *BindData, opts ...client.CallOption) (*UserData, error) {
	req := c.c.NewRequest(c.name, "UserService.Bind", in)
	out := new(UserData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Unbind(ctx context.Context, in *UnbindData, opts ...client.CallOption) (*UserData, error) {
	req := c.c.NewRequest(c.name, "UserService.Unbind", in)
	out := new(UserData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) User(ctx context.Context, in *SessionData, opts ...client.CallOption) (*UserData, error) {
	req := c.c.NewRequest(c.name, "UserService.User", in)
	out := new(UserData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UpdateData, opts ...client.CallOption) (*UserData, error) {
	req := c.c.NewRequest(c.name, "UserService.Update", in)
	out := new(UserData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 密码登陆/验证码登陆/第三方权限登陆
	Login(context.Context, *LoginData, *SessionData) error
	// 创建用户
	Register(context.Context, *RegisterData, *SessionData) error
	// 绑定用户
	Bind(context.Context, *BindData, *UserData) error
	// //解绑用户
	Unbind(context.Context, *UnbindData, *UserData) error
	// 用户信息
	User(context.Context, *SessionData, *UserData) error
	// 更新用户信息
	Update(context.Context, *UpdateData, *UserData) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	type userService interface {
		Login(ctx context.Context, in *LoginData, out *SessionData) error
		Register(ctx context.Context, in *RegisterData, out *SessionData) error
		Bind(ctx context.Context, in *BindData, out *UserData) error
		Unbind(ctx context.Context, in *UnbindData, out *UserData) error
		User(ctx context.Context, in *SessionData, out *UserData) error
		Update(ctx context.Context, in *UpdateData, out *UserData) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Login(ctx context.Context, in *LoginData, out *SessionData) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) Register(ctx context.Context, in *RegisterData, out *SessionData) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *userServiceHandler) Bind(ctx context.Context, in *BindData, out *UserData) error {
	return h.UserServiceHandler.Bind(ctx, in, out)
}

func (h *userServiceHandler) Unbind(ctx context.Context, in *UnbindData, out *UserData) error {
	return h.UserServiceHandler.Unbind(ctx, in, out)
}

func (h *userServiceHandler) User(ctx context.Context, in *SessionData, out *UserData) error {
	return h.UserServiceHandler.User(ctx, in, out)
}

func (h *userServiceHandler) Update(ctx context.Context, in *UpdateData, out *UserData) error {
	return h.UserServiceHandler.Update(ctx, in, out)
}
