// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usersrv/user.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	//手机号密码登陆
	Signup(ctx context.Context, in *SignupReq, opts ...client.CallOption) (*AuthRsp, error)
	//短信验证码登陆
	SignupByCaptcha(ctx context.Context, in *SignupByCaptchaReq, opts ...client.CallOption) (*AuthRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Signup(ctx context.Context, in *SignupReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.Signup", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SignupByCaptcha(ctx context.Context, in *SignupByCaptchaReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.SignupByCaptcha", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	//手机号密码登陆
	Signup(context.Context, *SignupReq, *AuthRsp) error
	//短信验证码登陆
	SignupByCaptcha(context.Context, *SignupByCaptchaReq, *AuthRsp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Signup(ctx context.Context, in *SignupReq, out *AuthRsp) error
		SignupByCaptcha(ctx context.Context, in *SignupByCaptchaReq, out *AuthRsp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Signup(ctx context.Context, in *SignupReq, out *AuthRsp) error {
	return h.UserServiceHandler.Signup(ctx, in, out)
}

func (h *userServiceHandler) SignupByCaptcha(ctx context.Context, in *SignupByCaptchaReq, out *AuthRsp) error {
	return h.UserServiceHandler.SignupByCaptcha(ctx, in, out)
}
