// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_srv/order.proto

package order_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Province             string   `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Items struct {
	//商品类别 默认为product
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	//商品编号
	SkuId int64 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	//商品标题
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	//商品规格
	Spec string `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	//重量
	Weight int64 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	//商品单价
	Price int64 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	//商品数量 quantity
	Qty int64 `protobuf:"varint,7,opt,name=qty,proto3" json:"qty,omitempty"`
	//商品单位
	Unit string `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	//实际需支付金额
	Payment              int64    `protobuf:"varint,9,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{1}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Items) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *Items) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Items) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Items) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Items) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Items) GetQty() int64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *Items) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Items) GetPayment() int64 {
	if m != nil {
		return m.Payment
	}
	return 0
}

type Order struct {
	//订单号
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	//详细项目
	Items []*Items `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	//订单总额
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	//订单优惠金额
	Discount int64 `protobuf:"varint,4,opt,name=discount,proto3" json:"discount,omitempty"`
	//订单实际需支付
	Payment int64 `protobuf:"varint,5,opt,name=payment,proto3" json:"payment,omitempty"`
	//支付状态
	PayState int64 `protobuf:"varint,6,opt,name=pay_state,json=payState,proto3" json:"pay_state,omitempty"`
	//支付时间
	PayAt string `protobuf:"bytes,7,opt,name=pay_at,json=payAt,proto3" json:"pay_at,omitempty"`
	//订单状态
	OrderState int64 `protobuf:"varint,8,opt,name=order_state,json=orderState,proto3" json:"order_state,omitempty"`
	//地址
	Address *Address `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	//更新时间
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	//创建时间
	CreatedAt            string   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *Order) GetItems() []*Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Order) GetDiscount() int64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Order) GetPayment() int64 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *Order) GetPayState() int64 {
	if m != nil {
		return m.PayState
	}
	return 0
}

func (m *Order) GetPayAt() string {
	if m != nil {
		return m.PayAt
	}
	return ""
}

func (m *Order) GetOrderState() int64 {
	if m != nil {
		return m.OrderState
	}
	return 0
}

func (m *Order) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

//创建订单
type CreateReq struct {
	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	//根据access_token区分商户
	// string access_token=1;
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{3}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *CreateReq) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

//订单
type OrderRsp struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRsp) Reset()         { *m = OrderRsp{} }
func (m *OrderRsp) String() string { return proto.CompactTextString(m) }
func (*OrderRsp) ProtoMessage()    {}
func (*OrderRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{4}
}

func (m *OrderRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRsp.Unmarshal(m, b)
}
func (m *OrderRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRsp.Marshal(b, m, deterministic)
}
func (m *OrderRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRsp.Merge(m, src)
}
func (m *OrderRsp) XXX_Size() int {
	return xxx_messageInfo_OrderRsp.Size(m)
}
func (m *OrderRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRsp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRsp proto.InternalMessageInfo

func (m *OrderRsp) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

//订单查询
type QueryReq struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	OrderNo              string   `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{5}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *QueryReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type QueryListReq struct {
	Pn                   int32    `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`
	Ps                   int32    `protobuf:"varint,2,opt,name=ps,proto3" json:"ps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryListReq) Reset()         { *m = QueryListReq{} }
func (m *QueryListReq) String() string { return proto.CompactTextString(m) }
func (*QueryListReq) ProtoMessage()    {}
func (*QueryListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0aa79a9508f442, []int{6}
}

func (m *QueryListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListReq.Unmarshal(m, b)
}
func (m *QueryListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListReq.Marshal(b, m, deterministic)
}
func (m *QueryListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListReq.Merge(m, src)
}
func (m *QueryListReq) XXX_Size() int {
	return xxx_messageInfo_QueryListReq.Size(m)
}
func (m *QueryListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListReq proto.InternalMessageInfo

func (m *QueryListReq) GetPn() int32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *QueryListReq) GetPs() int32 {
	if m != nil {
		return m.Ps
	}
	return 0
}

func init() {
	proto.RegisterType((*Address)(nil), "order_srv.Address")
	proto.RegisterType((*Items)(nil), "order_srv.Items")
	proto.RegisterType((*Order)(nil), "order_srv.Order")
	proto.RegisterType((*CreateReq)(nil), "order_srv.CreateReq")
	proto.RegisterType((*OrderRsp)(nil), "order_srv.OrderRsp")
	proto.RegisterType((*QueryReq)(nil), "order_srv.QueryReq")
	proto.RegisterType((*QueryListReq)(nil), "order_srv.QueryListReq")
}

func init() { proto.RegisterFile("order_srv/order.proto", fileDescriptor_dc0aa79a9508f442) }

var fileDescriptor_dc0aa79a9508f442 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6a, 0xd4, 0x50,
	0x10, 0x36, 0x49, 0xb3, 0x9b, 0xcc, 0x16, 0x29, 0xc7, 0x56, 0x8e, 0x15, 0xb1, 0xe4, 0x42, 0x7a,
	0x21, 0x2b, 0x6c, 0x11, 0xaf, 0x57, 0xf1, 0xa2, 0x20, 0x8a, 0xe9, 0x03, 0x2c, 0x31, 0x39, 0xb4,
	0xb1, 0xdd, 0xe4, 0xf4, 0x9c, 0xc9, 0x96, 0x3c, 0x89, 0xcf, 0xe1, 0x6b, 0xf8, 0x02, 0xbe, 0x8e,
	0xcc, 0x9c, 0x93, 0x74, 0x17, 0x7f, 0xc0, 0xbb, 0xf9, 0x66, 0xf2, 0xcd, 0x7c, 0xdf, 0xcc, 0x21,
	0x70, 0xd4, 0x9a, 0x4a, 0x99, 0x95, 0x35, 0x9b, 0x57, 0x1c, 0xcd, 0xb5, 0x69, 0xb1, 0x15, 0xe9,
	0x98, 0xce, 0xbe, 0x05, 0x30, 0x5d, 0x56, 0x95, 0x51, 0xd6, 0x0a, 0x01, 0x7b, 0x4d, 0xb1, 0x56,
	0x32, 0x38, 0x09, 0x4e, 0xd3, 0x9c, 0x63, 0x71, 0x08, 0xb1, 0xbe, 0x6a, 0x1b, 0x25, 0x43, 0x4e,
	0x3a, 0x20, 0x24, 0x4c, 0xcb, 0xb6, 0x6b, 0xd0, 0xf4, 0x32, 0xe2, 0xfc, 0x00, 0xc5, 0x31, 0x24,
	0xda, 0xb4, 0x9b, 0xba, 0x29, 0x95, 0xdc, 0xe3, 0xd2, 0x88, 0xa9, 0x7f, 0x59, 0x63, 0x2f, 0x63,
	0xd7, 0x9f, 0x62, 0xea, 0x54, 0xb8, 0xf1, 0x72, 0xe2, 0x3a, 0x79, 0x98, 0xfd, 0x08, 0x20, 0x3e,
	0x47, 0xb5, 0x66, 0x5d, 0xd8, 0xeb, 0x51, 0x17, 0xc5, 0xe2, 0x08, 0x26, 0xf6, 0xba, 0x5b, 0xd5,
	0x15, 0x0b, 0x8b, 0xf2, 0xd8, 0x5e, 0x77, 0xe7, 0x15, 0xc9, 0xc5, 0x1a, 0x6f, 0x94, 0x97, 0xe5,
	0x00, 0x35, 0xb0, 0x5a, 0x95, 0x5e, 0x10, 0xc7, 0xe2, 0x31, 0x4c, 0xee, 0x54, 0x7d, 0x79, 0x85,
	0x2c, 0x27, 0xca, 0x3d, 0x62, 0xc3, 0xa6, 0x2e, 0x15, 0xcb, 0x89, 0x72, 0x07, 0xc4, 0x01, 0x44,
	0xb7, 0xd8, 0xcb, 0x29, 0xe7, 0x28, 0xa4, 0x9e, 0x5d, 0x53, 0xa3, 0x4c, 0x5c, 0x4f, 0x8a, 0xc9,
	0x8c, 0x2e, 0xfa, 0xb5, 0x6a, 0x50, 0xa6, 0xfc, 0xe5, 0x00, 0xb3, 0x9f, 0x21, 0xc4, 0x9f, 0x68,
	0xe9, 0xe2, 0x09, 0x24, 0x6e, 0xfb, 0x4d, 0xeb, 0x0d, 0x4d, 0x19, 0x7f, 0x6c, 0xc5, 0x0b, 0x88,
	0x6b, 0x32, 0x2c, 0xc3, 0x93, 0xe8, 0x74, 0xb6, 0x38, 0x98, 0x8f, 0x67, 0x9a, 0xf3, 0x22, 0x72,
	0x57, 0x66, 0x93, 0x2d, 0x16, 0x37, 0x6c, 0x32, 0xca, 0x1d, 0xa0, 0xcd, 0x57, 0xb5, 0xe5, 0x3b,
	0xb0, 0xd1, 0x28, 0x1f, 0xf1, 0xb6, 0xb0, 0x78, 0x47, 0x98, 0x78, 0x0a, 0xa9, 0x2e, 0xfa, 0x95,
	0xc5, 0x02, 0x07, 0xcb, 0x89, 0x2e, 0xfa, 0x0b, 0xc2, 0xb4, 0x64, 0x2a, 0x16, 0xc8, 0xc6, 0xe9,
	0xfa, 0x45, 0xbf, 0x44, 0xf1, 0x1c, 0x66, 0x5e, 0x19, 0xb3, 0x12, 0x66, 0x01, 0xa7, 0x1c, 0xef,
	0xe5, 0xfd, 0x51, 0x69, 0x0f, 0xb3, 0x85, 0xd8, 0xb2, 0xe2, 0x5f, 0xdb, 0x78, 0x68, 0xf1, 0x0c,
	0xa0, 0xd3, 0x55, 0x81, 0xaa, 0xa2, 0x49, 0xc0, 0x93, 0x52, 0x9f, 0x59, 0x22, 0x95, 0x4b, 0xa3,
	0x86, 0xf2, 0xcc, 0x95, 0x7d, 0x66, 0x89, 0xd9, 0x7b, 0x48, 0xdf, 0x31, 0xc8, 0xd5, 0x2d, 0x9d,
	0xe9, 0xeb, 0x1d, 0xfa, 0xbd, 0x52, 0x48, 0x3b, 0xe5, 0xd1, 0xfc, 0x4c, 0x76, 0x77, 0xca, 0xf7,
	0xc8, 0x5d, 0x39, 0x5b, 0x40, 0xe2, 0xb0, 0xd5, 0xf7, 0x9c, 0xe0, 0xdf, 0x9c, 0x37, 0x90, 0x7c,
	0xee, 0x94, 0xe9, 0xff, 0x3c, 0x79, 0xfb, 0xd0, 0xe1, 0xce, 0xa1, 0xb3, 0x39, 0xec, 0x33, 0xf1,
	0x43, 0x6d, 0x91, 0xc8, 0x0f, 0x21, 0xd4, 0x0d, 0x73, 0xe3, 0x3c, 0xd4, 0x0d, 0x63, 0xcb, 0x24,
	0xc2, 0x76, 0xf1, 0x3d, 0x80, 0x7d, 0x9e, 0x7c, 0xa1, 0xcc, 0x86, 0x9e, 0xe3, 0x6b, 0x98, 0xbc,
	0xed, 0xaa, 0x4b, 0x85, 0xe2, 0x70, 0x4b, 0xdc, 0xb8, 0x87, 0xe3, 0x47, 0xbf, 0x49, 0xb6, 0x3a,
	0x7b, 0x40, 0x34, 0xf7, 0xcd, 0xff, 0xd1, 0xce, 0x86, 0xb7, 0xbb, 0x5d, 0x1f, 0x9c, 0xff, 0x85,
	0xf4, 0x65, 0xc2, 0xbf, 0x9a, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x5b, 0xef, 0x0f,
	0x83, 0x04, 0x00, 0x00,
}
